[package]
name = "ichigo"
version = "0.1.0"
edition = "2024"

[[bin]]
name = "ichigo"
path = "src/main.rs"

[dependencies]
clap = { version = "4", features = ["derive"] }
serde = { version = "1", features = ["derive"] }
serde_yaml = "0.9"
reqwest = { version = "0.12", features = ["blocking", "json"] }
serde_json = "1"
anyhow = "1"
colored = "2"
colored_json = "5"
